atxbirdcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name ='about'), 
    path('birds/', views.birds_index, name='index'), 
    path('birds/<int:bird_id>', views.birds_detail, name='detail'), 
    path('birds/create/', views.BirdCreate.as_view(), name='birds_create'), 
    path('birds/<int:pk>/update/', views.BirdUpdate.as_view(), name='birds_update'),
    path('birds/<int:pk>/delete/', views.BirdDelete.as_view(), name='birds_delete'),
    path('birds/<int:bird_id>/add_location/', views.add_location, name='add_location'),
    path('birds/<int:bird_id>/assoc_trait/<int:trait_id>/', views.assoc_trait, name='assoc_trait'),
    path('birds/<int:bird_id>/unassoc_trait/<int:trait_id>/', views.unassoc_trait, name='unassoc_trait'),
    path('birds/<int:bird_id>/add_photo/', views.add_photo, name='add_photo'),
    path('traits/', views.TraitList.as_view(), name='traits_index'),
    path('traits/<int:pk>/', views.TraitDetail.as_view(), name='traits_detail'),
    path('traits/create/', views.TraitCreate.as_view(), name='traits_create'),
    path('traits/<int:pk>/update/', views.TraitUpdate.as_view(), name='traits_update'),
    path('traits/<int:pk>/delete/', views.TraitDelete.as_view(), name='traits_delete'), 
    path('accounts/signup', views.signup, name='signup'), 
] 

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date 
from django.contrib.auth.models import User

LOCATIONS = (
    ('N', 'North'),
    ('S', 'South'),
    ('E', 'East'),
    ('W', 'West')
)

class Trait(models.Model):
    name = models.CharField(max_length=50)
    color= models.CharField(max_length=20)

    def __str__(self):
        return self.name 
    
    def get_absolute_url(self):
        return reverse('traits_detail', kwargs={'pk': self.id})

class Bird(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    traits = models.ManyToManyField(Trait)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self): 
        return self.name 
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'bird_id': self.id})

class Location(models.Model):
    date = models.DateField('location date')
    location = models.CharField(
        max_length=1, 
        choices=LOCATIONS, 
        default=LOCATIONS[0][0]
    )
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_location_display()} on {self.date}" 

    class Meta:
        ordering = ['-date']
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    bird = models.ForeignKey(Bird, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for bird_id: {self.bird_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm 
from .models import Location 

class LocationForm(ModelForm):
    class Meta: 
        model = Location
        fields = ['date', 'location']

main_app/views.py
from django.shortcuts import render, redirect 
from django.views.generic.edit import CreateView, UpdateView, DeleteView  
from django.views.generic import ListView, DetailView 
from django.contrib.auth import login 
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.mixins import LoginRequiredMixin

import boto3
import uuid

from .models import Bird, Trait, Photo 
from .forms import LocationForm

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'atxbirdcollector'

class BirdCreate(LoginRequiredMixin, CreateView):
    model = Bird
    fields = ['name', 'breed', 'description', 'age']
    
    def form_valid(self, form): 
        form.instance.user = self.request.user
        return super().form_valid(form)
    

class BirdUpdate(LoginRequiredMixin, UpdateView):
    model = Bird
    fields = ['breed', 'description', 'age']

class BirdDelete(LoginRequiredMixin, DeleteView):
    model = Bird
    success_url = '/birds/'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def birds_index(request):
    birds = Bird.objects.all()
    return render(request, 'birds/index.html', {'birds': birds})

@login_required
def birds_detail(request, bird_id):
    bird = Bird.objects.get(id=bird_id)
    traits_bird_doesnt_have = Trait.objects.exclude(id__in = bird.traits.all().values_list('id'))
    location_form = LocationForm()
    return render(request, 'birds/detail.html', {
        'bird': bird, 'location_form': location_form,
        'traits': traits_bird_doesnt_have
  })

@login_required
def add_location(request, bird_id):
    form = LocationForm(request.POST)
    if form.is_valid():
        new_location = form.save(commit=False)
        new_location.bird_id = bird_id
        new_location.save()
    return redirect('detail', bird_id=bird_id)

@login_required
def assoc_trait(request, bird_id, trait_id):
    Bird.objects.get(id=bird_id).traits.add(trait_id)
    return redirect('detail', bird_id=bird_id)

@login_required
def unassoc_trait(request, bird_id, trait_id):
    Bird.objects.get(id=bird_id).traits.remove(trait_id)
    return redirect('detail', bird_id=bird_id)

class TraitList(LoginRequiredMixin, ListView):
    model = Trait 

class TraitDetail(LoginRequiredMixin, DetailView):
    model = Trait 

class TraitCreate(LoginRequiredMixin, CreateView):
    model = Trait 
    fields = '__all__'

class TraitUpdate(LoginRequiredMixin, UpdateView):
    model = Trait 
    fields = ['name', 'color']

class TraitDelete(LoginRequiredMixin, DeleteView):
    model = Trait 
    success_url = '/traits/'

def add_photo(request, bird_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file: 
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try: 
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f'{S3_BASE_URL}{BUCKET}/{key}'
            photo = Photo(url=url, bird_id=bird_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', bird_id=bird_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sing up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About ATX Bird Collector</h1>
<hr />
<p>Track your birds!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>ATX Bird Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li>
            <a href="/" class="left brand-logo">&nbsp;&nbsp;Bird Collector</a>
          </li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'traits_create' %}">Add a Trait</a></li>
          <li><a href="{% url 'traits_index' %}">View All Traits</a></li>
          <li><a href="{% url 'birds_create' %}">Add a Bird</a></li>
          <li><a href="{% url 'index' %}">View All My Birds</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %} {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">
      All Rights Reserved, &copy; 2019 ATX Bird Collector &nbsp;
    </div>
  </footer>
</body>

</html>

main_app/templates/birds/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Bird Details</h1>

<div class='row'>
  <div class='col s6'>
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ bird.name }}</span>
        <p>Breed: {{ bird.breed }}</p>
        <p>Description: {{ bird.description }}</p>
        {% if bird.age > 0 %}
        <p>Age: {{ bird.age }}</p>
        {% else %}
        <p>Age: Bird</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'birds_update' bird.id %}">Edit</a>
        <a href="{% url 'birds_delete' bird.id %}">Delete</a>
      </div>
    </div>
    <!-- Insert pic markup here -->
    {% for photo in bird.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' bird.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
  </div>
  <div class='col s6'>
    <form action="{% url 'add_location' bird.id %}" method='post'>
      {% csrf_token %}
      {{ location_form.as_p }}
      <input type='submit' class='btn' value='Add Location'>
    </form>
    <table class='striped'>
      <thead>
        <tr>
          <th>Date</th>
          <th>Location</th>
        </tr>
      </thead>
      <tbody>
        {% for location in bird.location_set.all %}
        <tr>
          <td>{{ location.date }}</td>
          <td>{{ location.get_location_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ bird.name }}'s Traits</h3>
    {% if bird.traits.count %}
    {% for trait in bird.traits.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color: {{ trait.color }}">{{ trait.color }}</span> {{ trait.name }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'unassoc_trait' bird.id trait.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>No Traits :(</h5>
    {% endif %}
  </div>

  <!-- avail traits come after this line -->
  <div class="col s6">
    <h3>Available Traits</h3>
    {% if traits.count %}
    {% for trait in traits.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color: {{ trait.color }}">{{ trait.color }}</span> {{ trait.name }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_trait' bird.id trait.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>{{bird.name}} Already Has All Traits Available</h5>
    {% endif %}
  </div>
</div>


<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  var selectEl = document.getElementById('id_location');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/birds/index.html
{% extends 'base.html' %} {% block content %}

<h1>Bird List</h1>

{% for bird in birds %}
<a href="{% url 'detail' bird.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ bird.name }}</span>
      <p>Breed: {{ bird.breed }}</p>
      <p>Description: {{ bird.description }}</p>
      {% if bird.age > 0 %}
      <p>Age: {{ bird.age }}</p>
      {% else %}
      <p>Age: Kitten</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/bird_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Bird</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' bird.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/bird_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Bird</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/trait_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Trait</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'traits_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/trait_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Trait Details</h1>

<div class="row">
    <div class="col s6 col-offset-3">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ trait.name }}</span>
                <p>Color: {{ trait.color }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'traits_update' trait.id %}">Edit</a>
                <a href="{% url 'traits_delete' trait.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/trait_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Trait</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}

    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/trait_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Trait List</h1>

{% for trait in trait_list %}
<a href="{% url 'traits_detail' trait.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ trait.name }}</span>
            <p>Color: {{ trait.color }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}